baseURL = 'http://localhost:1313/'
locale = 'en-gb'
title = 'The Cyanotic bytes'
theme = 'PaperMod'
enableRobotsTXT = true

[pagination]
pagerSize = 20

[services]

[markup.highlight]
style = "dracula"

[params]
author = "Orfeo Ciano"
description = "Orfeo Ciano's personal website"
keywords = ["blog", "developer", "personal"]
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostMeta = true
ShowReadingTime = true
ShowToc = true
comments = true

[params.homeInfoParams]
Title = "The Cyanotic Bytes"
Content = "A software engineer writing about programming, emulation, retro gaming, and other nerdy rabbit holes."

[params.assets]
favicon = "images/favicon-32.png"
favicon16x16 = "images/favicon-16.png"
favicon32x32 = "images/favicon-32.png"
apple_touch_icon = "images/favicon-32.png"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.socialIcons]]
name = "github"
url = "https://github.com/otacon/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/cyanotic87"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/orfeo-ciano/"

[params.googleTagManager]
id = "GTM-PSHWNFQV"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[menu.main]]
name = "Archives"
weight = 2
url = "archives/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[menu.main]]
name = "About"
weight = 4
url = "about/"
